### ISSUE TITLE
sqlserver导入报错 不允许为null

### ISSUE THREAD

**Issue by zjfsdnu** [zlzforever/ClickHouseMigrator#7]
报错如下：
WARN: DROP TABLE IF EXISTS deer_him_sys_v5.equip_center;
Progress: 0 rows (0 rows/s.)ERROR: System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Int32'.
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ClickHouse.Ado.Impl.ColumnTypes.SimpleColumnType`1.ValuesFromConst(IEnumerable objects)
   at ClickHouse.Ado.ClickHouseCommand.Execute(Boolean readResponse, ClickHouseConnection connection)
   at ClickHouse.Ado.ClickHouseCommand.ExecuteNonQuery()
   at ClickHouseMigrator.Migrator.<>c__DisplayClass14_0.<Migrate>b__2() in /Users/lewis/github/ClickHouseMigrator/src/ClickHouseMigrator/Migrator.cs:line 166

Elapsed 0 sec. Processed 145 rows (145 rows/s.)

**Comment by zjfsdnu** [comment]
将ck的字段改为nullable类型 依然报错
ERROR: System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Nullable`1[System.Int32]'.

**Comment by zlzforever** [comment]
可以提供一个 SQL Server 表的创建脚本，样例数据么

**Comment by ArchaicLier** [comment]
Same problem
ClickHouse table is empty

Programs:

- [ClickHouse Docker image](https://hub.docker.com/r/yandex/clickhouse-server) 
[21.3.20.1](https://hub.docker.com/layers/yandex/clickhouse-server/21.3.20.1/images/sha256-4eccfffb01d735ab7c1af9a97fbff0c532112a6871b2bb5fe5c478d86d247b7e?context=explore)
- SQL Server 12.0.6444.4
- [ClickHouseMigrator](https://github.com/zlzforever/ClickHouseMigrator)


Console command

`ps
chm --src sqlserver --src-host localhost --src-port 1433 --src-user user --src-password Password --src-database test --src-table test --drop-table true
`

Execution 

```ps
PS C:\Users\kulikovnv> chm --src sqlserver --src-host loacalhost --src-port 1433 --src-user user --src-password Password `
>>--src-database test --src-table test --drop-table true
INFO: Options: C:\Users\kulikovnv\.dotnet\tools\.store\clickhousemigrator\1.1.3\clickhousemigrator\1.1.3\tools\net5.0\any\chm.dll 
--src sqlserver --src-host localgost --src-port 1433 --src-user user --src-password Password --src-database test --src-table test --drop-table true
=======================================================================================================================
ClickHouse Migrator V1.0.8 MIT   zlzforever@163.com

--src            : data source: MySql, SqlServer, Excel etc
--src-host       : host of data source, for example: 192.168.90.100, **default value: 127.0.0.1**
--src-port       : port of data source, for example: 3306
--src-user       : user of data source
--src-password   : password of data source
--src-database   : database of data source
--src-table      : table of data source
--host           : Clickhouse host: 192.168.90.101, **default value: 127.0.0.1**
--port           : Clickhouse port, for example: 9000, **default value: 9000**
--user           : Clickhouse user
--password       : Clickhouse password
--database       : Clickhouse database, if this arg is null, will use --src-database as target database name
--table          : Clickhouse table, if this arg is null, will use --src-table as target table name
--thread         : how many thread use to insert data to ClickHouse, **default value: process count of your machine**
--batch          : how many rows insert to ClickHouse one time, **default value: 10000**
--drop-table     : whether drop the exits table in clickhouse before migrating, **default value: false**
--file           : File path of Excel etc
--sheets         : Which sheets will be migrated, columns are same in every sheet, used like: Sheet1,Sheet2,Sheet3
--start-row      :
--lowercase      : ignore the word case in clickhouse, **default value: true**

=======================================================================================================================
WARN: DROP TABLE IF EXISTS test.test;
Progress: 0 rows (0 rows/s.)ERROR: System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Int32'.
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ClickHouse.Ado.Impl.ColumnTypes.SimpleColumnType`1.ValuesFromConst(IEnumerable objects)
   at ClickHouse.Ado.ClickHouseCommand.Execute(Boolean readResponse, ClickHouseConnection connection)
   at ClickHouse.Ado.ClickHouseCommand.ExecuteNonQuery()
   at ClickHouseMigrator.Migrator.<>c__DisplayClass13_0.<Migrate>b__2() in /Users/lewis/github/ClickHouseMigrator/src/ClickHouseMigrator/Migrator.cs:line 165
ERROR: System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Int32'.
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ClickHouse.Ado.Impl.ColumnTypes.SimpleColumnType`1.ValuesFromConst(IEnumerable objects)
   at ClickHouse.Ado.ClickHouseCommand.Execute(Boolean readResponse, ClickHouseConnection connection)
   at ClickHouse.Ado.ClickHouseCommand.ExecuteNonQuery()
   at ClickHouseMigrator.Migrator.<>c__DisplayClass13_0.<Migrate>b__2() in /Users/lewis/github/ClickHouseMigrator/src/ClickHouseMigrator/Migrator.cs:line 165
ERROR: System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Int32'.
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ClickHouse.Ado.Impl.ColumnTypes.SimpleColumnType`1.ValuesFromConst(IEnumerable objects)
   at ClickHouse.Ado.ClickHouseCommand.Execute(Boolean readResponse, ClickHouseConnection connection)
   at ClickHouse.Ado.ClickHouseCommand.ExecuteNonQuery()
   at ClickHouseMigrator.Migrator.<>c__DisplayClass13_0.<Migrate>b__2() in /Users/lewis/github/ClickHouseMigrator/src/ClickHouseMigrator/Migrator.cs:line 165
ERROR: System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Int32'.
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ClickHouse.Ado.Impl.ColumnTypes.SimpleColumnType`1.ValuesFromConst(IEnumerable objects)
   at ClickHouse.Ado.ClickHouseCommand.Execute(Boolean readResponse, ClickHouseConnection connection)
   at ClickHouse.Ado.ClickHouseCommand.ExecuteNonQuery()
   at ClickHouseMigrator.Migrator.<>c__DisplayClass13_0.<Migrate>b__2() in /Users/lewis/github/ClickHouseMigrator/src/ClickHouseMigrator/Migrator.cs:line 165
ERROR: System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Int32'.
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ClickHouse.Ado.Impl.ColumnTypes.SimpleColumnType`1.ValuesFromConst(IEnumerable objects)
   at ClickHouse.Ado.ClickHouseCommand.Execute(Boolean readResponse, ClickHouseConnection connection)
   at ClickHouse.Ado.ClickHouseCommand.ExecuteNonQuery()
   at ClickHouseMigrator.Migrator.<>c__DisplayClass13_0.<Migrate>b__2() in /Users/lewis/github/ClickHouseMigrator/src/ClickHouseMigrator/Migrator.cs:line 165
ERROR: System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Int32'.
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ClickHouse.Ado.Impl.ColumnTypes.SimpleColumnType`1.ValuesFromConst(IEnumerable objects)
   at ClickHouse.Ado.ClickHouseCommand.Execute(Boolean readResponse, ClickHouseConnection connection)
   at ClickHouse.Ado.ClickHouseCommand.ExecuteNonQuery()
   at ClickHouseMigrator.Migrator.<>c__DisplayClass13_0.<Migrate>b__2() in /Users/lewis/github/ClickHouseMigrator/src/ClickHouseMigrator/Migrator.cs:line 165
ERROR: System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Int32'.
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ClickHouse.Ado.Impl.ColumnTypes.SimpleColumnType`1.ValuesFromConst(IEnumerable objects)
   at ClickHouse.Ado.ClickHouseCommand.Execute(Boolean readResponse, ClickHouseConnection connection)
   at ClickHouse.Ado.ClickHouseCommand.ExecuteNonQuery()
   at ClickHouseMigrator.Migrator.<>c__DisplayClass13_0.<Migrate>b__2() in /Users/lewis/github/ClickHouseMigrator/src/ClickHouseMigrator/Migrator.cs:line 165
Progress: 80000 rows (40000 rows/s.)ERROR: System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Int32'.
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ClickHouse.Ado.Impl.ColumnTypes.SimpleColumnType`1.ValuesFromConst(IEnumerable objects)
   at ClickHouse.Ado.ClickHouseCommand.Execute(Boolean readResponse, ClickHouseConnection connection)
   at ClickHouse.Ado.ClickHouseCommand.ExecuteNonQuery()
   at ClickHouseMigrator.Migrator.<>c__DisplayClass13_0.<Migrate>b__2() in /Users/lewis/github/ClickHouseMigrator/src/ClickHouseMigrator/Migrator.cs:line 165

Elapsed 4 sec. Processed 80000 rows (20000 rows/s.)
```

SqlServer table structure:

![src-table](https://user-images.githubusercontent.com/55849349/227531831-b062aa37-51bb-407f-b749-9aa870ad6be9.png)

Clickhouse table structure generated by [ClickHouseMigrator](https://github.com/zlzforever/ClickHouseMigrator):

![ch-table](https://user-images.githubusercontent.com/55849349/227532094-e487c6f3-686a-4265-8058-e6a1a87469e1.png)
